let ele = document.getElementById("div1");
ele.style.backgroundColor = "yellow";
ele.style.margin = "20px";
ele.style.padding = "10px";
ele.style.fontSize = "18px";
ele.style.fontWeight = "bold";
ele.style.height = "200px";
ele.style.width = "300px";
ele.style.color = "rgb(52,104,250)"